### PR TITLE
Check for validity of R-vine matrices

### PR DESCRIPTION
**Pull request by tnagler**
re #186 

Added checks for several conditions that must be satisfied by an R-vine matrix. The checks are actually redundant, `check_upper_tri()`, `check_antidiagonal`, `check_columns()` are violated whenever `check_proximity_condition()` is, but I kept them to allow for more informative error messages. They could be ommited for sake of performance, which I haven't looked into so far.

### CODE REVIEW

**Comment by tvatter** [comment]
While I find this version with "one function per check" very intuitive, it is also a bit naïve and I am concerned about performance:

1. Could you bring the loop over the trees in `check_matrix`?
2. In `rvinecopulib`, since we are creating a new objects all the time, we'll need to either accept a huge overhead (from the double loop in `check_proximity_condition`) or find a way to bypass the `check_matrix`. I would be in favor of the later, and a simple solution would be a `safe` argument to the `RVineMatrix`'s constructor.

**Comment by tnagler** [comment]
1. Since loops have almost no overhead in C++, running the same loop several times shouldn't be a problem.
2. Yes, we should only check the validity of the matrix only once. We could write an R-class equivalent to `RVineMatrix` which does the check and must be used when constructing a `vinecop_dist`. When an `RVineMatrix`-equivalent object is passed to cpp, we should not repeat the checks. This will be easy to do with a flag in the constructor. We should also omit the checks at the end of `Vinecop(data)` as soon we are sure that there is no flaw in our logic.

**Comment by tnagler** [comment]
1. Checked with a single loop in dimensions from 10 to 1000. There is no difference between a single loop and several loops in sequence. I'd prefer to keep the modularized version then, the code is much cleaner.

**Comment by tvatter** [comment]
1. If there is no difference in performance, then I completely agree.
2. Exactly what I had in mind!

**Pull request merged**
