### PR TITLE
fix loglik-related bugs [NOT READY TO MERGE]

### PR DESCRIPTION
**Pull request by tvatter**

### CODE REVIEW

**Comment by tvatter** [comment]
So, there is still something that I don't like: this flip won't work for models in flip_by_rotation such that the log-likelihood has not been set (i.e., if you try to flip a Clayton with custom initialization).

**Comment by tnagler** [comment]
How about
``` cpp
inline void Bicop::flip()
{
    double ll = bicop_->get_loglik();
    // flipping
    // ...
    bicop_->set_loglik(ll);
}
```
and throwing the error from `Bicop::get_loglik()` rather than `AbstractBicop::get_loglik()`?

**Comment by tnagler** [comment]
Oh, OK that's roughly what you did.

**Comment by tvatter** [comment]
Actually, moving the error throwing is clearly the best idea.

**Pull request merged**
