### PR TITLE
allow to omit R-vine matrix check in Vinecop ctors

### PR DESCRIPTION
**Pull request by tnagler**

### CODE REVIEW

**Comment by tvatter** [comment]
Wouldn't it also be nice to use this PR to add the ctors allowing to pass a RVineMatrix object directly?

**Comment by tnagler** [comment]
Do we need such constructors?

**Comment by tvatter** [comment]
They are quite natural IMO: why should we only allow the user to pass a matrix? Currently, the RVineMatrix is documented and part of the user-facing API...

**Comment by tvatter** [comment]
Anyway, we can always add this later.

**Pull request merged**
