### PR TITLE
allow 'loglik' as selection criterion

### PR DESCRIPTION
**Pull request by tnagler**

### CODE REVIEW

**Comment by tvatter** [comment]
Didn't you mention that this was the mother of all bad ideas?

**Comment by tnagler** [comment]
Yeah, but I don't think we should disallow it. For example, Dani's  selection algorithm for D-vine regression is based on log-likelihoods (with option for AIC/BIC correction). There may be other use cases that we don't see right now. In any case, there's really no need to patronize the users if it doesn't cost us anything to keep it more flexible.

**Comment by tvatter** [comment]
OK, no problem. In any case, I noticed that you removed the proper casts that are required for Ripley!

**Comment by tnagler** [comment]
Oh damn, seems like I branched out of a wrong branch. I'll just make a new PR.

**Comment by tvatter** [comment]
Yeah just noticed

**Pull request closed without merging**
