### PR TITLE
parallelize loglik/bic etc

### PR DESCRIPTION
**Pull request by tnagler**

### CODE REVIEW

**Comment by tvatter** [comment]
Shouldn't we also be able to compute the loglik/AIC/BIC from the saved value (e.g., with a default empty `const Eigen::MatrixXd &u`) ?

**Comment by tnagler** [comment]
Shouldn't this rather be `get_aic()` etc?

**Comment by tvatter** [comment]
Agreed, it's just to avoid recomputing in R whenever we can avoid.

**Comment by tnagler** [comment]
So either we add a `nobs` data member, or we can't do `get_bic()`. The "recomputing" in R is really just multiplying two numbers and adding another one, so I think that overhead would be negligible (if it even exists).

**Comment by tvatter** [comment]
Ah true... well, I guess that, if we save the loglik, for a fitted object, it makes sense to save nobs too.

**Comment by tnagler** [comment]
alright added the nobs

**Comment by tvatter** [comment]
Just one thing: shouldn't `compute_mbicv_penalty` be `calculate_mbicv_penalty` or to be consistent with `compute_npars` ?

**Comment by tnagler** [comment]
fixed

**Pull request merged**
