### PR TITLE
parallelize whenever possible even more

### PR DESCRIPTION
**Pull request by tvatter**

### CODE REVIEW

**Comment by tvatter** [comment]
I don't think that having `#ifndef INTERFACED_FROM_R` also in `include/vinecopulib/misc/tools_parallel.hpp` is a good idea. Is it necessary?

**Comment by tnagler** [comment]
If we want to have `map_on_pool()` in the same file, I think it is.

**Comment by tvatter** [comment]
Then I would take the Threads stuff in a separate file and get e.g. tools_threads.

Also, 1e-2 seems like a big difference if the models are equals no?

**Comment by tnagler** [comment]
OK, will do the tools_threads then.

I had `EXPECT_DOUBLE_EQ()` before and it failed on the 8th digit or something. The log likelihood is around 900, so I don't think 2 digits is really that large. Didn't want to spend too long figuring out how far we can go, just do see random failures again ;)

**Comment by tvatter** [comment]
Perfect then!

**Comment by tnagler** [comment]
Kept the ThreadPool in tools_parallel, can also make a new namespace tools_thread if you prefer.

**Comment by tvatter** [comment]
Nah, it's fine as it is now, my suggestion was mostly to do avoid having the R-stuff hidden by the Threadpool implementation.

**Comment by tnagler** [comment]
Yeah makes sense.

**Pull request merged**
